name: Feature Request
description: Propose a new feature for this agent
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to add?
      placeholder: Describe the feature...
    validations:
      required: true
  - type: textarea
    id: verification
    attributes:
      label: Verification
      description: How can we verify this feature works?
      placeholder: "npm run X shows Y..."
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
